#!/usr/bin/env python
# -*- coding: utf-8 -*-

# import modules --------------------------------------------------------------
from __future__ import division  # handy tool for division

import random

from psychopy import visual, core, event, gui

# Settings --------------------------------------------------------------------

WinWidth = 1000
WinHeigth = 500
FullScreen = False
text_size = 0.07

# Set up window ---------------------------------------------------------------
win = visual.Window(
    size=(WinWidth, WinHeigth),
    fullscr=FullScreen,
    monitor='testMonitor',
    allowGUI=None,
    checkTiming=True
)
    # Create static period
ScreenHZ = win.getActualFrameRate(nIdentical=60,
                                  nMaxFrames=100,
                                  nWarmUpFrames=10,
                                  threshold=1)
ISI = core.StaticPeriod(screenHz=ScreenHZ, win=win)

mouse = event.Mouse(visible=False)

routineTimer = core.CountdownTimer()
clock = core.Clock()
press = False
continueRoutine = True
start_count = False
start_response = False
buttons, times = mouse.getPressed(getTime=True)

error = visual.TextStim(win,
                        text="False",
                        alignHoriz='center',
                        pos=(0, 0))



while continueRoutine:
    for trial in range(5):
        if trial == 5:
            continueRoutine = False
            break

        interval = random.uniform(1, 5)
        start_count = False
        start_response = False
        t = 0
        clock.reset()
        if clock.getTime() < interval and buttons[0]:
            start_count = False
            mouse.clickReset()
            win.flip()
            print('2')
        # core.wait(interval)
        if clock.getTime() >= interval and not buttons[0]:
            clock.reset()
            start_count = True
            win.flip()
            print('3')
            while start_count is True:
                start_response = True
                count = clock.getTime()
                clock_stim = visual.TextStim(win,
                                             text=str(count)[:5],
                                             alignHoriz='center',
                                             pos=(0, 0))
                clock_stim.draw()
                win.flip()
                print('4')
                if buttons[0] and start_response is True:
                    start_count = False
                    start_response = False
                    clock_stim.draw()
                    win.flip()
                    # core.wait(1)
                    mouse.clickReset()
                    #trial = trial + 1
                    print('5')
                if continueRoutine:
                    win.flip()

                if event.getKeys(keyList=["escape"]):
                    core.quit()
